### ISSUE TITLE
syntax highlighting issue on device categories starting with a number or including a slash (/)

### ISSUE THREAD

**Issue by Fxzzi** [luckasRanarison/tree-sitter-hyprlang#11]
Hey there! Only a super small issue, but i don't get syntax highlighting on this part of my `hyprland.conf`

```
device:tpps/2-elan-trackpoint {
	accel_profile = flat
}
```
![image](https://github.com/luckasRanarison/tree-sitter-hyprlang/assets/18248986/3cf6ca77-4192-4ad0-bd29-3d264bb973f8)

It seems to be related to the fact that the name of my device includes a slash, as removing it makes the highlighting show up (obviously now the config doesn't work)

Similarly, it seems the highlighting also does not work if the device name begins with a number.

**Comment by luckasRanarison** [comment]
It should be fixed now.
