### ISSUE TITLE
Incorrect highlighting when the device has a complex name

### ISSUE THREAD

**Issue by kjlo** [luckasRanarison/tree-sitter-hyprlang#12]
The touchpad has a weird device name with colons in between. When I remove them the highlighting works properly but not the configuration.
![photo_2024-01-15_11-07-36](https://github.com/luckasRanarison/tree-sitter-hyprlang/assets/79338048/9d9043c4-722b-4836-a051-4b9bb6f70a76)

This shows the proper device name with hyprctl devices (first device in the list):
![photo_2024-01-15_11-07-20](https://github.com/luckasRanarison/tree-sitter-hyprlang/assets/79338048/7af3005d-d772-42a5-94ed-cbb2ec89bb88)

Highlighting after removing colons:
![photo_2024-01-15_11-07-45](https://github.com/luckasRanarison/tree-sitter-hyprlang/assets/79338048/15966c43-9de8-4d6b-bfb7-3253f0f2966f)
![photo_2024-01-15_11-07-50](https://github.com/luckasRanarison/tree-sitter-hyprlang/assets/79338048/2b199da9-ecdb-4353-ba21-afcbd8fd16a6)

**Comment by luckasRanarison** [comment]
It should be fixed now, I hope there are no other symbols not taken in account in device name...

**Comment by kjlo** [comment]
Thanks, now it's resolved.
